version: '3'

services:
  postgres:
    image: postgres:9
    container_name: councilmatic_postgres
    environment:
      - POSTGRES_PASSWORD=str0ng*p4ssw0rd
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../councilmatic-website-data:/var/lib/postgresql/data
    ports:
      - 6432:5432
  solr:
    image: solr
    container_name: councilmatic_solr
    ports:
     - 8983:8983
    volumes:
      - ../councilmatic-solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
  webserver:
    image: ekkus93/councilmatic-website
    container_name: councilmatic_website
    ports:
      - 8000:8000 
      - 8001:8001
    volumes:
      - ../councilmatic:/home/django/councilmatic
    depends_on:
      - postgres
      - solr
      